# Generated by Django 6.0.8 on 2026-08-04 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('task_id', models.CharField(help_text='Human-readable ID e.g. TSK-101', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('CODE_REVIEW', 'Code Review'), ('TESTING', 'Testing'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='TODO', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('progress', models.IntegerField(default=0, help_text='0 to 100')),
                ('labels', models.CharField(blank=True, help_text='Comma-separated labels', max_length=255, null=True)),
            ],
            options={
                'db_table': 'aureon_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('file', models.FileField(upload_to='task_attachments/')),
                ('filename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aureon_task_attachments',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'aureon_task_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('action', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aureon_task_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
