# Generated by Django 6.0.8 on 2026-08-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Consecutive failed login counter for security lockout.'),
        ),
        migrations.AddField(
            model_name='user',
            name='lockout_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp until which account is locked out.', null=True),
        ),
    ]
