# Generated by Django 6.0.8 on 2026-08-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_preset_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_preset',
            field=models.TextField(blank=True, null=True),
        ),
    ]
