# Generated by Django 6.0.8 on 2026-08-06 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_initial'),
        ('roles', '0003_alter_role_code_alter_role_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiontoken',
            name='roles',
        ),
        migrations.AlterField(
            model_name='permissiontoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='permissiontoken',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='permissiontoken',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.'),
        ),
        migrations.AlterField(
            model_name='permissiontoken',
            name='module',
            field=models.CharField(db_index=True, help_text='Domain module e.g. projects, tasks, bugs', max_length=50),
        ),
        migrations.AlterField(
            model_name='permissiontoken',
            name='token',
            field=models.CharField(db_index=True, help_text='Token code e.g. projects.create', max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='permissiontoken',
            table='tbl_permission',
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='permissions.permissiontoken')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='roles.role')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
