# Generated by Django 6.0.8 on 2026-08-04 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('role_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('action', models.CharField(help_text='e.g. USER_LOGIN, TASK_UPDATE, REPORT_DOWNLOAD', max_length=100)),
                ('resource', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aureon_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
