# Generated by Django 6.0.8 on 2026-08-04 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UPDATED', 'Task Updated'), ('SPRINT_STARTED', 'Sprint Started'), ('BUG_ASSIGNED', 'Bug Assigned'), ('REPO_CONNECTED', 'Repository Connected'), ('PROJECT_UPDATED', 'Project Updated')], max_length=40)),
                ('read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
            ],
            options={
                'db_table': 'aureon_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
