# Generated by Django 6.0.8 on 2026-08-06 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UPDATED', 'Task Updated'), ('BUG_ASSIGNED', 'Bug Assigned'), ('SPRINT_STARTED', 'Sprint Started'), ('SPRINT_COMPLETED', 'Sprint Completed'), ('REPO_CONNECTED', 'Repository Connected'), ('PROJECT_UPDATED', 'Project Updated')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='tbl_notification',
        ),
    ]
