# Generated by Django 6.0.8 on 2026-08-04 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('name', models.CharField(help_text='e.g. aureon/core-backend', max_length=200)),
                ('repository_url', models.URLField()),
                ('platform', models.CharField(default='GitHub', max_length=50)),
                ('language', models.CharField(default='Python', max_length=50)),
                ('default_branch', models.CharField(default='main', max_length=50)),
                ('is_connected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aureon_repositories',
            },
        ),
    ]
