# Generated by Django 6.0.8 on 2026-08-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='is_connected',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='language',
        ),
        migrations.AddField(
            model_name='repository',
            name='clone_status',
            field=models.CharField(default='CLONED', max_length=50),
        ),
        migrations.AddField(
            model_name='repository',
            name='github_repository_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_sync_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.CharField(default='aureon-saas', max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='visibility',
            field=models.CharField(default='PRIVATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(db_index=True, help_text='e.g. aureon/core-backend', max_length=200),
        ),
        migrations.AlterModelTable(
            name='repository',
            table='tbl_repository',
        ),
    ]
