# Generated by Django 6.0.8 on 2026-08-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sprint',
            name='velocity',
            field=models.IntegerField(default=0, help_text='Sprint story points velocity'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], db_index=True, default='PLANNING', max_length=20),
        ),
        migrations.AlterModelTable(
            name='sprint',
            table='tbl_sprint',
        ),
    ]
