# Generated by Django 6.0.8 on 2026-08-04 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('code', models.CharField(choices=[('ROLE_ADMIN', 'System Administrator'), ('ROLE_PM', 'Project Manager'), ('ROLE_LEAD', 'Team Lead'), ('ROLE_DEV', 'Developer'), ('ROLE_QA', 'QA Engineer')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=5, help_text='Priority level (1=highest)')),
            ],
            options={
                'db_table': 'aureon_roles',
                'ordering': ['level'],
            },
        ),
    ]
