# Generated by Django 6.0.8 on 2026-08-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ROLE_ADMIN', 'Administrator'), ('ROLE_PM', 'Project Manager'), ('ROLE_LEAD', 'Team Lead'), ('ROLE_DEV', 'Developer'), ('ROLE_QA', 'QA Engineer')], db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.'),
        ),
        migrations.AlterModelTable(
            name='role',
            table='tbl_role',
        ),
    ]
