# Generated by Django 6.0.8 on 2026-08-04 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSmell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('file', models.CharField(max_length=255)),
                ('line', models.IntegerField()),
                ('rule', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(default='MAJOR', max_length=20)),
                ('effort_minutes', models.IntegerField(default=15)),
            ],
            options={
                'db_table': 'aureon_code_smells',
            },
        ),
        migrations.CreateModel(
            name='SonarQubeScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('project_key', models.CharField(max_length=100)),
                ('quality_gate', models.CharField(choices=[('PASSED', 'Passed'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], default='PASSED', max_length=20)),
                ('coverage', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('reliability_rating', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='A', max_length=2)),
                ('maintainability_rating', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='A', max_length=2)),
                ('security_rating', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='A', max_length=2)),
                ('technical_debt_minutes', models.IntegerField(default=0)),
                ('code_smells', models.IntegerField(default=0)),
                ('bugs', models.IntegerField(default=0)),
                ('vulnerabilities', models.IntegerField(default=0)),
                ('duplications_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'db_table': 'aureon_sonarqube_scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
