# Generated by Django 6.0.8 on 2026-08-06 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_business_architect_and_more'),
        ('sonarqube', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonarqubescan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sonarqubescan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sonarqubescan',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='QualityGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='PASSED', max_length=20)),
                ('rules_count', models.IntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_quality_gate',
            },
        ),
        migrations.CreateModel(
            name='CodeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('gate_status', models.CharField(db_index=True, default='PASSED', max_length=20)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('maintainability_rating', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='A', max_length=2)),
                ('reliability_rating', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='A', max_length=2)),
                ('security_rating', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='A', max_length=2)),
                ('technical_debt_minutes', models.IntegerField(default=0)),
                ('code_smells_count', models.IntegerField(default=0)),
                ('bugs_count', models.IntegerField(default=0)),
                ('vulnerabilities_count', models.IntegerField(default=0)),
                ('duplications_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_analyses', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('quality_gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sonarqube.qualitygate')),
            ],
            options={
                'db_table': 'tbl_code_analysis',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.DeleteModel(
            name='CodeSmell',
        ),
        migrations.DeleteModel(
            name='SonarQubeScan',
        ),
    ]
