# Generated by Django 6.0.8 on 2026-08-06 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architected_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(db_index=True, help_text='Short key prefix e.g. ACCA', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='HIGH', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='IN_PROGRESS', max_length=30),
        ),
        migrations.AlterModelTable(
            name='milestone',
            table='tbl_project_milestone',
        ),
        migrations.AlterModelTable(
            name='project',
            table='tbl_project',
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('role_in_project', models.CharField(default='Developer', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_project_member',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
