# Generated by Django 6.0.8 on 2026-08-06 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('role_code', models.CharField(db_index=True, max_length=50)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('json_data', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_dashboard_cache',
                'ordering': ['-created_at'],
            },
        ),
    ]
