# Generated by Django 6.0.8 on 2026-08-04 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('capacity_percentage', models.IntegerField(default=100, help_text='Team capacity workload %')),
            ],
            options={
                'db_table': 'aureon_teams',
                'ordering': ['name'],
            },
        ),
    ]
