# Generated by Django 6.0.8 on 2026-08-04 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('commit_hash', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=150)),
                ('author_email', models.CharField(max_length=150)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('committed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'aureon_github_commits',
                'ordering': ['-committed_at'],
            },
        ),
        migrations.CreateModel(
            name='GithubIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('issue_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(default='open', max_length=20)),
            ],
            options={
                'db_table': 'aureon_github_issues',
            },
        ),
        migrations.CreateModel(
            name='GithubPullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('pr_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=100)),
                ('base_branch', models.CharField(default='main', max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEW', 'In Review'), ('MERGED', 'Merged'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('ci_status', models.CharField(default='PASSING', max_length=30)),
            ],
            options={
                'db_table': 'aureon_github_pull_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
