import React, { useState } from 'react';
import { Card, CardHeader, CardTitle, CardDescription } from '../common/Card';
import { Table, TableRow, TableCell } from '../common/Table';
import { Button } from '../common/Button';
import { Badge } from '../common/Badge';
import { FileBarChart, Download, FileSpreadsheet, Plus, CheckCircle2 } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export const ReportsSection = ({ reports }) => {
  const { showToast } = useAuth();
  const [reportType, setReportType] = useState('Code Quality Compliance');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = (e) => {
    e.preventDefault();
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      showToast(`New ${reportType} report generated successfully!`, 'success');
    }, 1500);
  };

  const handleDownloadPDF = (name) => {
    const textContent = `====================================================\nAUREON SOFTWARE ENGINEERING PLATFORM REPORT\n====================================================\nReport Name: ${name}\nGenerated Date: ${new Date().toISOString()}\nPlatform Health Score: 94.5%\nCode Complexity Index: LOW (1.8)\nMaintainability Index: 88.4%\nSecurity Audit Scenarios Passed: 17/17\n====================================================\n`;
    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${name.replace(/\s+/g, '_')}_Report.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    showToast(`Downloaded document: ${name}`, 'info');
  };

  const handleExportCSV = (name) => {
    const csvContent = `Report Name,Metric,Value,Status\n${name},Health Score,94.5%,PASSED\n${name},Pylint Metric,9.8/10,EXCELLENT\n${name},Radon Cyclomatic Complexity,1.8,OPTIMAL\n${name},Security Audit Scenarios,17/17,PASSED\n`;
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${name.replace(/\s+/g, '_')}_Dataset.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    showToast(`Exported CSV dataset: ${name}`, 'info');
  };

  return (
    <Card>
      <CardHeader>
        <div>
          <CardTitle icon={FileBarChart}>Engineering Reports & Audits</CardTitle>
          <CardDescription>Generate, download, and export technical compliance reports</CardDescription>
        </div>
      </CardHeader>

      {/* Report Generator Controls */}
      <form onSubmit={handleGenerate} className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-4 bg-[#111827] border border-[#334155] rounded-[12px] mb-6">
        <div className="sm:col-span-2">
          <label className="block text-xs font-semibold uppercase text-[#CBD5E1] mb-1">
            Select Report Type
          </label>
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
            className="w-full px-3 py-2 bg-[#1F2937] text-[#F8FAFC] text-xs rounded-[12px] border border-[#334155] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
          >
            <option value="Code Quality Compliance">Monthly Code Quality & Health Compliance</option>
            <option value="Developer Velocity">Developer Velocity & Sprint Metrics</option>
            <option value="Security Dependency Vulnerabilities">Repository Dependency Vulnerability Scan</option>
            <option value="Architecture Complexity">Architecture Cyclomatic Complexity Matrix</option>
          </select>
        </div>

        <div className="flex items-end">
          <Button
            type="submit"
            variant="primary"
            size="md"
            fullWidth
            isLoading={isGenerating}
            icon={Plus}
          >
            Generate Report
          </Button>
        </div>
      </form>

      {/* Generated Reports History Table */}
      <h4 className="text-xs font-semibold uppercase text-[#CBD5E1] tracking-wider mb-2">
        Report Audit History
      </h4>
      <Table headers={['Report Name', 'Format', 'File Size', 'Generated By', 'Date', 'Actions']}>
        {reports.map((rep) => (
          <TableRow key={rep.id}>
            <TableCell className="font-semibold text-[#F8FAFC]">
              {rep.name}
            </TableCell>
            <TableCell>
              <Badge variant={rep.format === 'PDF' ? 'error' : 'success'} size="sm">
                {rep.format}
              </Badge>
            </TableCell>
            <TableCell>{rep.size}</TableCell>
            <TableCell>{rep.generatedBy}</TableCell>
            <TableCell className="text-xs text-[#94A3B8]">{rep.date}</TableCell>
            <TableCell>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleDownloadPDF(rep.name)}
                  className="p-1.5 bg-[#111827] hover:bg-[#2563EB]/20 text-[#38BDF8] rounded-lg border border-[#334155] transition-colors"
                  title="Download PDF"
                >
                  <Download className="w-3.5 h-3.5" />
                </button>
                <button
                  onClick={() => handleExportCSV(rep.name)}
                  className="p-1.5 bg-[#111827] hover:bg-[#10B981]/20 text-[#10B981] rounded-lg border border-[#334155] transition-colors"
                  title="Export CSV"
                >
                  <FileSpreadsheet className="w-3.5 h-3.5" />
                </button>
              </div>
            </TableCell>
          </TableRow>
        ))}
      </Table>
    </Card>
  );
};
