import React, { useState } from 'react';
import { Card, CardHeader, CardTitle, CardDescription } from '../common/Card';
import { Table, TableRow, TableCell } from '../common/Table';
import { Button } from '../common/Button';
import { Badge } from '../common/Badge';
import { FileBarChart, Download, FileSpreadsheet, Plus, CheckCircle2 } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export const ReportsSection = ({ reports }) => {
  const { showToast } = useAuth();
  const [reportType, setReportType] = useState('Code Quality Compliance');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = (e) => {
    e.preventDefault();
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      showToast(`New ${reportType} report generated successfully!`, 'success');
    }, 1500);
  };

  const handleDownloadPDF = (name) => {
    showToast(`Downloading PDF document: ${name}...`, 'info');
  };

  const handleExportCSV = (name) => {
    showToast(`Exporting CSV dataset: ${name}...`, 'info');
  };

  return (
    <Card>
      <CardHeader>
        <div>
          <CardTitle icon={FileBarChart}>Engineering Reports & Audits</CardTitle>
          <CardDescription>Generate, download, and export technical compliance reports</CardDescription>
        </div>
      </CardHeader>

      {/* Report Generator Controls */}
      <form onSubmit={handleGenerate} className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-4 bg-[#111827] border border-[#334155] rounded-[12px] mb-6">
        <div className="sm:col-span-2">
          <label className="block text-xs font-semibold uppercase text-[#CBD5E1] mb-1">
            Select Report Type
          </label>
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
            className="w-full px-3 py-2 bg-[#1F2937] text-[#F8FAFC] text-xs rounded-[12px] border border-[#334155] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
          >
            <option value="Code Quality Compliance">Monthly Code Quality & Health Compliance</option>
            <option value="Developer Velocity">Developer Velocity & Sprint Metrics</option>
            <option value="Security Dependency Vulnerabilities">Repository Dependency Vulnerability Scan</option>
            <option value="Architecture Complexity">Architecture Cyclomatic Complexity Matrix</option>
          </select>
        </div>

        <div className="flex items-end">
          <Button
            type="submit"
            variant="primary"
            size="md"
            fullWidth
            isLoading={isGenerating}
            icon={Plus}
          >
            Generate Report
          </Button>
        </div>
      </form>

      {/* Generated Reports History Table */}
      <h4 className="text-xs font-semibold uppercase text-[#CBD5E1] tracking-wider mb-2">
        Report Audit History
      </h4>
      <Table headers={['Report Name', 'Format', 'File Size', 'Generated By', 'Date', 'Actions']}>
        {reports.map((rep) => (
          <TableRow key={rep.id}>
            <TableCell className="font-semibold text-[#F8FAFC]">
              {rep.name}
            </TableCell>
            <TableCell>
              <Badge variant={rep.format === 'PDF' ? 'error' : 'success'} size="sm">
                {rep.format}
              </Badge>
            </TableCell>
            <TableCell>{rep.size}</TableCell>
            <TableCell>{rep.generatedBy}</TableCell>
            <TableCell className="text-xs text-[#94A3B8]">{rep.date}</TableCell>
            <TableCell>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleDownloadPDF(rep.name)}
                  className="p-1.5 bg-[#111827] hover:bg-[#2563EB]/20 text-[#38BDF8] rounded-lg border border-[#334155] transition-colors"
                  title="Download PDF"
                >
                  <Download className="w-3.5 h-3.5" />
                </button>
                <button
                  onClick={() => handleExportCSV(rep.name)}
                  className="p-1.5 bg-[#111827] hover:bg-[#10B981]/20 text-[#10B981] rounded-lg border border-[#334155] transition-colors"
                  title="Export CSV"
                >
                  <FileSpreadsheet className="w-3.5 h-3.5" />
                </button>
              </div>
            </TableCell>
          </TableRow>
        ))}
      </Table>
    </Card>
  );
};
