# Generated by Django 6.0.8 on 2026-08-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(db_index=True, default='SYSTEM', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='systemsetting',
            table='tbl_system_setting',
        ),
    ]
