# Generated by Django 6.0.8 on 2026-08-04 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHealthScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('score', models.IntegerField(help_text='Calculated score (0-100)')),
                ('task_completion_factor', models.FloatField(default=0.0)),
                ('sprint_progress_factor', models.FloatField(default=0.0)),
                ('sonarqube_factor', models.FloatField(default=0.0)),
                ('bugs_penalty', models.FloatField(default=0.0)),
                ('late_tasks_penalty', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aureon_project_health_scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
